version: "3.8"
services:
  postgres-db:
    container_name: acc-postgres
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: acc_dev
      POSTGRES_PASSWORD: acc_dev12
      POSTGRES_DB: acc_postgres
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgresql_data:
    driver: local